name: mlm
description: Music Linker Mobile.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.6
  provider: ^5.0.0
  http: ^0.13.3
  json_annotation: ^4.0.1
  cached_network_image: ^3.1.0
  flutter_cache_manager: ^3.1.2
  device_info: ^2.0.2
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.0
  json_serializable: ^4.1.3

flutter:
  uses-material-design: true
  generate: true
